apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::685184971264:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Z298Y3MQ1PH4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::685184971264:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-02T22:13:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1461"
  uid: 34a3d30b-3373-4b9e-9705-937593e9d620
